FROM python:3.8-slim-buster
WORKDIR /app
COPY ./habit_tracker ./habit_tracker
COPY ./requirements.txt ./wsgi.py ./config.py ./
RUN pip3 install -r ./requirements.txt
ENV FLASK_APP habit_tracker
ENV FLASK_ENV development
EXPOSE 3000
CMD ["flask", "run", "--host", "0.0.0.0", "--port", "5000"]