services:
  habit-tracker:
    build:
      context: .
      dockerfile: Dockerfile.dev.backend
    volumes:
      - './habit_tracker:/app/habit_tracker'
      - './wsgi.py:/app/wsgi.py'
      - './config.py:/app/config.py'
      - './secrets.py:/app/secrets.py'
    ports:
      - '5000:5000'
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev.frontend
      args:
        # Backend port number that React sends requests to
        - REACT_APP_PORT=5000
    volumes:
      - './public:/app/public'
      - './src:/app/src'
    ports:
      - '3000:3000'